"""Dynamic Protobuf message class construction using betterproto.

Builds betterproto.Message subclasses at runtime from a :class:`ModelInfo`,
so each registered model gets real Protobuf request/response types without
requiring a ``protoc`` code-generation step.
"""

from __future__ import annotations

import dataclasses
from typing import Any, List, get_args, get_origin

import betterproto

from blazerpc.codegen.proto import _sanitize_name
from blazerpc.runtime.registry import ModelInfo
from blazerpc.types import _TensorType

# ---------------------------------------------------------------------------
# Shared TensorProto message — emitted once, reused by all tensor fields.
# Mirrors the .proto definition generated by ProtoGenerator.
# ---------------------------------------------------------------------------

_TensorProtoMsg = dataclasses.dataclass(
    type(
        "TensorProto",
        (betterproto.Message,),
        {
            "__annotations__": {
                "shape": List[int],
                "dtype": str,
                "data": bytes,
            },
            "shape": betterproto.int64_field(1),
            "dtype": betterproto.string_field(2),
            "data": betterproto.bytes_field(3),
        },
    )
)

# Mapping from Python scalar types to the appropriate betterproto field factory.
_SCALAR_FIELD: dict[type, Any] = {
    float: betterproto.float_field,
    int: betterproto.int64_field,
    str: betterproto.string_field,
    bool: betterproto.bool_field,
    bytes: betterproto.bytes_field,
}

# Mapping from Python scalar types to their List equivalents for repeated fields.
_LIST_ANNOTATION: dict[type, type] = {
    float: List[float],
    int: List[int],
    str: List[str],
    bool: List[bool],
    bytes: List[bytes],
}


def _field_spec(py_type: Any, field_num: int) -> tuple[Any, Any]:
    """Return ``(annotation, betterproto_field_default)`` for *py_type*.

    Handles:
    - ``_TensorType`` → nested ``TensorProto`` message field
    - ``list[X]``     → repeated scalar field
    - Python scalars  → scalar field
    - Fallback        → ``bytes_field``
    """
    if isinstance(py_type, _TensorType):
        return _TensorProtoMsg, betterproto.message_field(field_num)

    origin = get_origin(py_type)
    if origin is list:
        args = get_args(py_type)
        inner = args[0] if args else bytes
        factory = _SCALAR_FIELD.get(inner, betterproto.bytes_field)
        ann = _LIST_ANNOTATION.get(inner, List[bytes])
        return ann, factory(field_num)

    if isinstance(py_type, type) and py_type in _SCALAR_FIELD:
        return py_type, _SCALAR_FIELD[py_type](field_num)

    # Fallback for dict or unknown types.
    return bytes, betterproto.bytes_field(field_num)


def build_message_classes(model: ModelInfo) -> tuple[type, type]:
    """Build betterproto ``(RequestClass, ResponseClass)`` for *model*.

    The returned classes are proper :class:`betterproto.Message` subclasses
    that support ``.SerializeToString()`` / ``.parse(data)`` round-trips.
    """
    # ---- Request ----
    req_annotations: dict[str, Any] = {}
    req_defaults: dict[str, Any] = {}
    for field_num, (name, py_type) in enumerate(model.input_types.items(), start=1):
        ann, default = _field_spec(py_type, field_num)
        req_annotations[name] = ann
        req_defaults[name] = default

    req_ns = {"__annotations__": req_annotations, **req_defaults}
    request_cls: type = dataclasses.dataclass(
        type(f"{_sanitize_name(model.name)}Request", (betterproto.Message,), req_ns)
    )

    # ---- Response ----
    if model.output_type is not None:
        res_ann, res_default = _field_spec(model.output_type, 1)
        res_ns: dict[str, Any] = {
            "__annotations__": {"result": res_ann},
            "result": res_default,
        }
    else:
        res_ns = {"__annotations__": {}}

    response_cls: type = dataclasses.dataclass(
        type(f"{_sanitize_name(model.name)}Response", (betterproto.Message,), res_ns)
    )

    return request_cls, response_cls
